- components/Nav.js
- components/Utilities/LoginModal.js
- components/Utilities/VerifyModal.js
- pages/checkout.js
- styles/abstract/_base.scss
- styles/abstract/_utilities.scss
- styles/abstract/_variables.scss
- styles/app.scss
- styles/pages/checkout/_checkout.scss
- styles/utilities/_login.scss
- styles/utilities/_navbar.scss
Design the checkout page in its mobile, table and desktop version.
> [Maquetar checkout page](https://app.asana.com/0/0/1203304102218150/f)
1.  `/pages/checkout.js`
2.  `/style/pages/checkout/_checkout.scss`
> [FEATURE]: layout checkout page, mobile, tablet and desktop version

- pages/dashboard.js
- pages/thanks.js
- styles/app.scss
- styles/pages/dashboard/_bookings.scss
I layout dashboard page and integrate grid js for render data bookings
> [Maquetar booking dashboard client page](https://app.asana.com/0/0/1203304102218152/f)
​
1.  `/page/dashboard.js`
2.  `/styles/pages/dashboard/_bookings.scss`
​
> [FEATURE]: layout dashboard page

- components/Nav.js
- pages/_document.js
- pages/reserve.js
- styles/app.scss
- styles/pages/bookings/_reserve.scss
- styles/utilities/_login.scss
I layout reserve details page
> [Maquetar booking details page](https://app.asana.com/0/0/1203304102218153/f)
1.  `/pages/reserve.js`
2.  `/styles/pages/bookings/_reserve.scss`
> [FEATURE]: layout reserve detail page

- .env
- components/CardsExperience.js
- components/Footer.js
- components/Home/FloteBikes.js
- components/Home/Hero.js
- components/Home/Places.js
- components/Layouts.js
- components/Nav.js
- components/Utilities/LoginModal.js
- components/Utilities/VerifyModal.js
- context/AuthContext.js
- next.config.js
- package-lock.json
- package.json
- pages/_app.js
- pages/_document.js
- pages/api/hello.js
- pages/checkout.js
- pages/confirm-email.js
- pages/dashboard.js
- pages/index.js
- pages/reserve.js
- pages/thanks.js
- styles/abstract/_utilities.scss
> [FEATURE]: integration login app

- next.config.js
add new confing en next.config file for test compativility the images .webp format
> [UPDATE]: add new confing en next.config file

- next.config.js
- styles/app.scss
add new config in next.config file
> [UPDATE]: add new config in next.config file

- components/Nav.js
- styles/utilities/_navbar.scss
resolver layout mobile version
> [FIX]: resolver layout mobile version

- components/Nav.js
> [UPDATE]: delete console.log

- components/Nav.js
- styles/utilities/_navbar.scss
> {UPDATE]: delete console.log

- .env
- .env.development
- components/Home/FloteBikes.js
- components/Home/Hero.js
- components/Nav.js
- context/AuthContext.js
- context/auth-user/index.js
- hooks/auth-user.js
- pages/_app.js
- pages/dashboard.js
- services/config.js
- services/users/auth.js
- styles/abstract/_base.scss
- styles/pages/home/_flotebikes.scss
- Add field validation login
- add toast for response of login action
- add services module for request to API
> [FEATURE]:  Login validations

- components/Home/FloteBikes.js
- components/Home/Hero.js
- components/Home/Places.js
- pages/index.js
- Resolve hydratation problem in places section
> [FIX]:  hydratation places section

- pages/index.js
> [FIX]: run build, delete commets

- package-lock.json
- styles/pages/checkout/_stripe.scss
> changing form stripe className

- components/home/FloteBikes.js
- pages/motos/[slug].js
- styles/pages/home/_hero.scss
[Slug (gets)] (https://app.asana.com/0/1202873144426895/1203450612087845/f)
the followinf files modified
1. `pages/motos/[slug].js`
> [FEATURE]: add slugo single moto, add group radio button for selected pickup

- components/Nav.js
- components/home/FloteBikes.js
- pages/dashboard.js
- services/bikes/motos.js
- services/users/auth.js
- change get data axios to fetch API
> [UPDATE]: change axios to Fetch API

- components/CheckoutForm.js
- components/Nav.js
- context/auth-user/index.js
- pages/checkout.js
- pages/confirm-email.js
- pages/dashboard.js
- pages/motos/[slug].js
- pages/motos/index.js
- pages/reserva/[id].js
- pages/thanks.js
- delete all console.log
- fix format date when date is undefined in map method
- Integration single reserve
> [UPDATE]: Valid format date

- components/CheckoutForm.js
- pages/reserva/[id].js
- services/bikes/motos.js
- services/reserves/reserve.js
- styles/pages/bookings/_reserve.scss
- Flow of completed reservation
- Tracking of completed reservation
> [Taks_name](https://app.asana.com/0/1202873144426895/1203450612087871/f)
1.  `/motos/[slug].js`
> [FEATURE]: Tracking of completed reservation

- components/Utilities/FormReserve.js
> Upload token mapbox

- components/Nav.js
- add create account with name
-
> add create account with name

- components/Nav.js
- components/home/Hero.js
- pages/motos/index.js
- pages/reserva/[id].js
Checking ortography everything is good!
> Ortography check

- components/Nav.js
- components/home/Hero.js
- pages/motos/index.js
- pages/reserva/[id].js
> [UPDATE]: check orthography

- components/Utilities/CardMoto.js
- components/home/FloteBikes.js
- components/home/Hero.js
- components/home/Places.js
- next.config.js
- package-lock.json
- package.json
- pages/_app.js
- pages/_document.js
- pages/index.js
- pages/reserva/[id].js
- styles/app.scss
- styles/pages/home/_flotebikes.scss
- styles/pages/home/_places.scss
- Fix swiper mobile version
- Change library swiper
> [FIX: swiper error mobile](https://app.asana.com/0/1202873144426895/1203535371860595/f)
1.  `/components/home/FloteBike.js`
2.  `/pages/index.js`
> [UPDATE]: Change library swiper

- components/Nav.js
- package-lock.json
- package.json
- pages/rutas/index.js
- styles/pages/routes/_routes.scss
- styles/utilities/_navbar.scss
- Handdle errore login, register, and verify account
- Fix initial lleter of udername
- Fix login and register modal in mobile version
1.  `/components/Nav.js`
2.  `/pages/rutas/index.js`
> [UPDATE]: Nav details

- components/Layouts.js
- components/Nav.js
- components/Utilities/FormReserve.js
- components/home/Hero.js
- components/home/Places.js
- components/home/SlideMotos.js
- pages/motos/[slug].js
- pages/motos/index.js
- pages/reserva/[id].js
- pages/rutas/[slug].js
- pages/rutas/index.js
- services/bikes/motos.js
- styles/abstract/_utilities.scss
- styles/pages/home/_places.scss
- styles/pages/routes/_routes.scss
- Add query params for filters
- Layout filter in routes pages
- Add like button in slider place in home
> [Taks_name](https://app.asana.com/0/1202873144426895/1203512801625668/f)
1. `components/Nav.js`
2. `components/Utilities/FormReserve.js`
3. `components/home/Places.js`
4. `pages/reserva/[id].js`
5. `services/bikes/motos.js`
6. `styles/pages/home/_places.scss`
> [UPDATE]: Add query params for filter

- components/Nav.js
- components/home/Places.js
- pages/favorites.js
- pages/rutas/index.js
- styles/pages/routes/_routes.scss
I created a new page for favorite sites for each customer, also i added a modal to login when someone tries to favorite a route.
1.  `/pages/favorites.js`
Please review my styles implementation
> [FEATURE]: Add favorites page

- components/Nav.js
- pages/motos/index.js
- pages/rutas/[slug].js
- services/bikes/motos.js
- fixed dates filters on motos page
> [FIX]: Fixed dates filter on /motos page

- pages/_app.js
> add google analytics
